/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright (C) 2024 KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package kiapi.schematic.types;

import "common/types/base_types.proto";

enum SchematicLayer
{
  SL_UNKNOWN = 0;

  // Corresponds to SCH_LAYER_ID::LAYER_WIRE
  SL_WIRE = 1;

  // Corresponds to SCH_LAYER_ID::LAYER_BUS
  SL_BUS = 2;

  // Corresponds to SCH_LAYER_ID::LAYER_NOTES
  SL_NOTES = 3;
}

/// Represents a schematic line segment, which may be a wire, bus, or graphical line
message Line
{
  kiapi.common.types.KIID    id     = 1;
  kiapi.common.types.Vector2 start  = 2;
  kiapi.common.types.Vector2 end    = 3;

  /**
   * One of: LAYER_BUS, LAYER_WIRE, LAYER_NOTES
   */
  SchematicLayer layer = 4;
}

message Text
{
  kiapi.common.types.Text text = 1;
}

message LocalLabel
{
  kiapi.common.types.KIID    id       = 1;
  kiapi.common.types.Vector2 position = 2;
  Text                       text     = 3;
}

message GlobalLabel
{
  kiapi.common.types.KIID    id       = 1;
  kiapi.common.types.Vector2 position = 2;
  Text                       text     = 3;
}

message HierarchicalLabel
{
  kiapi.common.types.KIID    id       = 1;
  kiapi.common.types.Vector2 position = 2;
  Text                       text     = 3;
}

message DirectiveLabel
{
  kiapi.common.types.KIID    id       = 1;
  kiapi.common.types.Vector2 position = 2;
  Text                       text     = 3;
}

/// A name/value pair for a schematic symbol field (e.g. "Reference", "Value")
message Field
{
  string name = 1;
  string value = 2;
}

/// Represents a schematic symbol (component instance) placed on a schematic.
/// The library symbol is resolved by lib_id when the item is created.
message Symbol
{
  kiapi.common.types.KIID id = 1;

  // Position of the symbol on the schematic, in nanometers
  kiapi.common.types.Vector2 position = 2;

  // The LIB_ID of the symbol to instantiate (e.g. nickname "Device", name "R")
  kiapi.common.types.LibraryIdentifier lib_id = 3;

  // Fields to set on the created symbol (Reference, Value, custom fields)
  repeated Field fields = 4;
}
